const countries = [
    { id: "afghanistan", name: "Afghanistan", flag: "https://flagcdn.com/256x192/af.png" },
    { id: "albania", name: "Albania", flag: "https://flagcdn.com/256x192/al.png" },
    { id: "algeria", name: "Algeria", flag: "https://flagcdn.com/256x192/dz.png" },
    { id: "andorra", name: "Andorra", flag: "https://flagcdn.com/256x192/ad.png" },
    { id: "angola", name: "Angola", flag: "https://flagcdn.com/256x192/ao.png" },
    { id: "antigua-and-barbuda", name: "Antigua and Barbuda", flag: "https://flagcdn.com/256x192/ag.png" },
    { id: "argentina", name: "Argentina", flag: "https://flagcdn.com/256x192/ar.png" },
    { id: "armenia", name: "Armenia", flag: "https://flagcdn.com/256x192/am.png" },
    { id: "australia", name: "Australia", flag: "https://flagcdn.com/256x192/au.png" },
    { id: "austria", name: "Austria", flag: "https://flagcdn.com/256x192/at.png" },
    { id: "azerbaijan", name: "Azerbaijan", flag: "https://flagcdn.com/256x192/az.png" },
    { id: "bahamas", name: "Bahamas", flag: "https://flagcdn.com/256x192/bs.png" },
    { id: "bahrain", name: "Bahrain", flag: "https://flagcdn.com/256x192/bh.png" },
    { id: "bangladesh", name: "Bangladesh", flag: "https://flagcdn.com/256x192/bd.png" },
    { id: "barbados", name: "Barbados", flag: "https://flagcdn.com/256x192/bb.png" },
    { id: "belarus", name: "Belarus", flag: "https://flagcdn.com/256x192/by.png" },
    { id: "belgium", name: "Belgium", flag: "https://flagcdn.com/256x192/be.png" },
    { id: "belize", name: "Belize", flag: "https://flagcdn.com/256x192/bz.png" },
    { id: "benin", name: "Benin", flag: "https://flagcdn.com/256x192/bj.png" },
    { id: "bhutan", name: "Bhutan", flag: "https://flagcdn.com/256x192/bt.png" },
    { id: "bolivia", name: "Bolivia", flag: "https://flagcdn.com/256x192/bo.png" },
    { id: "bosnia-and-herzegovina", name: "Bosnia and Herzegovina", flag: "https://flagcdn.com/256x192/ba.png" },
    { id: "botswana", name: "Botswana", flag: "https://flagcdn.com/256x192/bw.png" },
    { id: "brazil", name: "Brazil", flag: "https://flagcdn.com/256x192/br.png" },
    { id: "brunei", name: "Brunei", flag: "https://flagcdn.com/256x192/bn.png" },
    { id: "bulgaria", name: "Bulgaria", flag: "https://flagcdn.com/256x192/bg.png" },
    { id: "burkina-faso", name: "Burkina Faso", flag: "https://flagcdn.com/256x192/bf.png" },
    { id: "burundi", name: "Burundi", flag: "https://flagcdn.com/256x192/bi.png" },
    { id: "cabo-verde", name: "Cabo Verde", flag: "https://flagcdn.com/256x192/cv.png" },
    { id: "cambodia", name: "Cambodia", flag: "https://flagcdn.com/256x192/kh.png" },
    { id: "cameroon", name: "Cameroon", flag: "https://flagcdn.com/256x192/cm.png" },
    { id: "canada", name: "Canada", flag: "https://flagcdn.com/256x192/ca.png" },
    { id: "central-african-republic", name: "Central African Republic", flag: "https://flagcdn.com/256x192/cf.png" },
    { id: "chad", name: "Chad", flag: "https://flagcdn.com/256x192/td.png" },
    { id: "chile", name: "Chile", flag: "https://flagcdn.com/256x192/cl.png" },
    { id: "china", name: "China", flag: "https://flagcdn.com/256x192/cn.png" },
    { id: "colombia", name: "Colombia", flag: "https://flagcdn.com/256x192/co.png" },
    { id: "comoros", name: "Comoros", flag: "https://flagcdn.com/256x192/km.png" },
    { id: "congo-democratic-republic-of-the", name: "Congo (Democratic Republic of the)", flag: "https://flagcdn.com/256x192/cd.png" },
    { id: "congo-republic-of-the", name: "Congo (Republic of the)", flag: "https://flagcdn.com/256x192/cg.png" },
    { id: "costa-rica", name: "Costa Rica", flag: "https://flagcdn.com/256x192/cr.png" },
    { id: "croatia", name: "Croatia", flag: "https://flagcdn.com/256x192/hr.png" },
    { id: "cuba", name: "Cuba", flag: "https://flagcdn.com/256x192/cu.png" },
    { id: "cyprus", name: "Cyprus", flag: "https://flagcdn.com/256x192/cy.png" },
    { id: "czech-republic", name: "Czech Republic", flag: "https://flagcdn.com/256x192/cz.png" },
    { id: "denmark", name: "Denmark", flag: "https://flagcdn.com/256x192/dk.png" },
    { id: "djibouti", name: "Djibouti", flag: "https://flagcdn.com/256x192/dj.png" },
    { id: "dominica", name: "Dominica", flag: "https://flagcdn.com/256x192/dm.png" },
    { id: "dominican-republic", name: "Dominican Republic", flag: "https://flagcdn.com/256x192/do.png" },
    { id: "east-timor", name: "East Timor", flag: "https://flagcdn.com/256x192/tl.png" },
    { id: "ecuador", name: "Ecuador", flag: "https://flagcdn.com/256x192/ec.png" },
    { id: "egypt", name: "Egypt", flag: "https://flagcdn.com/256x192/eg.png" },
    { id: "el-salvador", name: "El Salvador", flag: "https://flagcdn.com/256x192/sv.png" },
    { id: "equatorial-guinea", name: "Equatorial Guinea", flag: "https://flagcdn.com/256x192/gq.png" },
    { id: "eritrea", name: "Eritrea", flag: "https://flagcdn.com/256x192/er.png" },
    { id: "estonia", name: "Estonia", flag: "https://flagcdn.com/256x192/ee.png" },
    { id: "eswatini", name: "Eswatini", flag: "https://flagcdn.com/256x192/sz.png" },
    { id: "ethiopia", name: "Ethiopia", flag: "https://flagcdn.com/256x192/et.png" },
    { id: "fiji", name: "Fiji", flag: "https://flagcdn.com/256x192/fj.png" },
    { id: "finland", name: "Finland", flag: "https://flagcdn.com/256x192/fi.png" },
    { id: "france", name: "France", flag: "https://flagcdn.com/256x192/fr.png" },
    { id: "gabon", name: "Gabon", flag: "https://flagcdn.com/256x192/ga.png" },
    { id: "gambia", name: "Gambia", flag: "https://flagcdn.com/256x192/gm.png" },
    { id: "georgia", name: "Georgia", flag: "https://flagcdn.com/256x192/ge.png" },
    { id: "germany", name: "Germany", flag: "https://flagcdn.com/256x192/de.png" },
    { id: "ghana", name: "Ghana", flag: "https://flagcdn.com/256x192/gh.png" },
    { id: "greece", name: "Greece", flag: "https://flagcdn.com/256x192/gr.png" },
    { id: "grenada", name: "Grenada", flag: "https://flagcdn.com/256x192/gd.png" },
    { id: "guatemala", name: "Guatemala", flag: "https://flagcdn.com/256x192/gt.png" },
    { id: "guinea", name: "Guinea", flag: "https://flagcdn.com/256x192/gn.png" },
    { id: "guinea-bissau", name: "Guinea-Bissau", flag: "https://flagcdn.com/256x192/gw.png" },
    { id: "guyana", name: "Guyana", flag: "https://flagcdn.com/256x192/gy.png" },
    { id: "haiti", name: "Haiti", flag: "https://flagcdn.com/256x192/ht.png" },
    { id: "honduras", name: "Honduras", flag: "https://flagcdn.com/256x192/hn.png" },
    { id: "hungary", name: "Hungary", flag: "https://flagcdn.com/256x192/hu.png" },
    { id: "iceland", name: "Iceland", flag: "https://flagcdn.com/256x192/is.png" },
    { id: "india", name: "India", flag: "https://flagcdn.com/256x192/in.png" },
    { id: "indonesia", name: "Indonesia", flag: "https://flagcdn.com/256x192/id.png" },
    { id: "iran", name: "Iran", flag: "https://flagcdn.com/256x192/ir.png" },
    { id: "iraq", name: "Iraq", flag: "https://flagcdn.com/256x192/iq.png" },
    { id: "ireland", name: "Ireland", flag: "https://flagcdn.com/256x192/ie.png" },
    { id: "israel", name: "Israel", flag: "https://flagcdn.com/256x192/il.png" },
    { id: "italy", name: "Italy", flag: "https://flagcdn.com/256x192/it.png" },
    { id: "ivory-coast", name: "Ivory Coast", flag: "https://flagcdn.com/256x192/ci.png" },
    { id: "jamaica", name: "Jamaica", flag: "https://flagcdn.com/256x192/jm.png" },
    { id: "japan", name: "Japan", flag: "https://flagcdn.com/256x192/jp.png" },
    { id: "jordan", name: "Jordan", flag: "https://flagcdn.com/256x192/jo.png" },
    { id: "kazakhstan", name: "Kazakhstan", flag: "https://flagcdn.com/256x192/kz.png" },
    { id: "kenya", name: "Kenya", flag: "https://flagcdn.com/256x192/ke.png" },
    { id: "kiribati", name: "Kiribati", flag: "https://flagcdn.com/256x192/ki.png" },
    { id: "kosovo", name: "Kosovo", flag: "https://flagcdn.com/256x192/xk.png" },
    { id: "kuwait", name: "Kuwait", flag: "https://flagcdn.com/256x192/kw.png" },
    { id: "kyrgyzstan", name: "Kyrgyzstan", flag: "https://flagcdn.com/256x192/kg.png" },
    { id: "laos", name: "Laos", flag: "https://flagcdn.com/256x192/la.png" },
    { id: "latvia", name: "Latvia", flag: "https://flagcdn.com/256x192/lv.png" },
    { id: "lebanon", name: "Lebanon", flag: "https://flagcdn.com/256x192/lb.png" },
    { id: "lesotho", name: "Lesotho", flag: "https://flagcdn.com/256x192/ls.png" },
    { id: "liberia", name: "Liberia", flag: "https://flagcdn.com/256x192/lr.png" },
    { id: "libya", name: "Libya", flag: "https://flagcdn.com/256x192/ly.png" },
    { id: "liechtenstein", name: "Liechtenstein", flag: "https://flagcdn.com/256x192/li.png" },
    { id: "lithuania", name: "Lithuania", flag: "https://flagcdn.com/256x192/lt.png" },
    { id: "luxembourg", name: "Luxembourg", flag: "https://flagcdn.com/256x192/lu.png" },
    { id: "madagascar", name: "Madagascar", flag: "https://flagcdn.com/256x192/mg.png" },
    { id: "malawi", name: "Malawi", flag: "https://flagcdn.com/256x192/mw.png" },
    { id: "malaysia", name: "Malaysia", flag: "https://flagcdn.com/256x192/my.png" },
    { id: "maldives", name: "Maldives", flag: "https://flagcdn.com/256x192/mv.png" },
    { id: "mali", name: "Mali", flag: "https://flagcdn.com/256x192/ml.png" },
    { id: "malta", name: "Malta", flag: "https://flagcdn.com/256x192/mt.png" },
    { id: "marshall-islands", name: "Marshall Islands", flag: "https://flagcdn.com/256x192/mh.png" },
    { id: "mauritania", name: "Mauritania", flag: "https://flagcdn.com/256x192/mr.png" },
    { id: "mauritius", name: "Mauritius", flag: "https://flagcdn.com/256x192/mu.png" },
    { id: "mexico", name: "Mexico", flag: "https://flagcdn.com/256x192/mx.png" },
    { id: "micronesia", name: "Micronesia", flag: "https://flagcdn.com/256x192/fm.png" },
    { id: "moldova", name: "Moldova", flag: "https://flagcdn.com/256x192/md.png" },
    { id: "monaco", name: "Monaco", flag: "https://flagcdn.com/256x192/mc.png" },
    { id: "mongolia", name: "Mongolia", flag: "https://flagcdn.com/256x192/mn.png" },
    { id: "montenegro", name: "Montenegro", flag: "https://flagcdn.com/256x192/me.png" },
    { id: "morocco", name: "Morocco", flag: "https://flagcdn.com/256x192/ma.png" },
    { id: "mozambique", name: "Mozambique", flag: "https://flagcdn.com/256x192/mz.png" },
    { id: "myanmar", name: "Myanmar", flag: "https://flagcdn.com/256x192/mm.png" },
    { id: "namibia", name: "Namibia", flag: "https://flagcdn.com/256x192/na.png" },
    { id: "nauru", name: "Nauru", flag: "https://flagcdn.com/256x192/nr.png" },
    { id: "nepal", name: "Nepal", flag: "https://flagcdn.com/256x192/np.png" },
    { id: "netherlands", name: "Netherlands", flag: "https://flagcdn.com/256x192/nl.png" },
    { id: "new-zealand", name: "New Zealand", flag: "https://flagcdn.com/256x192/nz.png" },
    { id: "nicaragua", name: "Nicaragua", flag: "https://flagcdn.com/256x192/ni.png" },
    { id: "niger", name: "Niger", flag: "https://flagcdn.com/256x192/ne.png" },
    { id: "nigeria", name: "Nigeria", flag: "https://flagcdn.com/256x192/ng.png" },
    { id: "north-korea", name: "North Korea", flag: "https://flagcdn.com/256x192/kp.png" },
    { id: "north-macedonia", name: "North Macedonia", flag: "https://flagcdn.com/256x192/mk.png" },
    { id: "norway", name: "Norway", flag: "https://flagcdn.com/256x192/no.png" },
    { id: "oman", name: "Oman", flag: "https://flagcdn.com/256x192/om.png" },
    { id: "pakistan", name: "Pakistan", flag: "https://flagcdn.com/256x192/pk.png" },
    { id: "palau", name: "Palau", flag: "https://flagcdn.com/256x192/pw.png" },
    { id: "panama", name: "Panama", flag: "https://flagcdn.com/256x192/pa.png" },
    { id: "papua-new-guinea", name: "Papua New Guinea", flag: "https://flagcdn.com/256x192/pg.png" },
    { id: "paraguay", name: "Paraguay", flag: "https://flagcdn.com/256x192/py.png" },
    { id: "peru", name: "Peru", flag: "https://flagcdn.com/256x192/pe.png" },
    { id: "philippines", name: "Philippines", flag: "https://flagcdn.com/256x192/ph.png" },
    { id: "poland", name: "Poland", flag: "https://flagcdn.com/256x192/pl.png" },
    { id: "portugal", name: "Portugal", flag: "https://flagcdn.com/256x192/pt.png" },
    { id: "qatar", name: "Qatar", flag: "https://flagcdn.com/256x192/qa.png" },
    { id: "romania", name: "Romania", flag: "https://flagcdn.com/256x192/ro.png" },
    { id: "russia", name: "Russia", flag: "https://flagcdn.com/256x192/ru.png" },
    { id: "rwanda", name: "Rwanda", flag: "https://flagcdn.com/256x192/rw.png" },
    { id: "saint-kitts-and-nevis", name: "Saint Kitts and Nevis", flag: "https://flagcdn.com/256x192/kn.png" },
    { id: "saint-lucia", name: "Saint Lucia", flag: "https://flagcdn.com/256x192/lc.png" },
    { id: "saint-vincent-and-the-grenadines", name: "Saint Vincent and the Grenadines", flag: "https://flagcdn.com/256x192/vc.png" },
    { id: "samoa", name: "Samoa", flag: "https://flagcdn.com/256x192/ws.png" },
    { id: "san-marino", name: "San Marino", flag: "https://flagcdn.com/256x192/sm.png" },
    { id: "sao-tome-and-principe", name: "Sao Tome and Principe", flag: "https://flagcdn.com/256x192/st.png" },
    { id: "saudi-arabia", name: "Saudi Arabia", flag: "https://flagcdn.com/256x192/sa.png" },
    { id: "senegal", name: "Senegal", flag: "https://flagcdn.com/256x192/sn.png" },
    { id: "serbia", name: "Serbia", flag: "https://flagcdn.com/256x192/rs.png" },
    { id: "seychelles", name: "Seychelles", flag: "https://flagcdn.com/256x192/sc.png" },
    { id: "sierra-leone", name: "Sierra Leone", flag: "https://flagcdn.com/256x192/sl.png" },
    { id: "singapore", name: "Singapore", flag: "https://flagcdn.com/256x192/sg.png" },
    { id: "slovakia", name: "Slovakia", flag: "https://flagcdn.com/256x192/sk.png" },
    { id: "slovenia", name: "Slovenia", flag: "https://flagcdn.com/256x192/si.png" },
    { id: "solomon-islands", name: "Solomon Islands", flag: "https://flagcdn.com/256x192/sb.png" },
    { id: "somalia", name: "Somalia", flag: "https://flagcdn.com/256x192/so.png" },
    { id: "south-africa", name: "South Africa", flag: "https://flagcdn.com/256x192/za.png" },
    { id: "south-korea", name: "South Korea", flag: "https://flagcdn.com/256x192/kr.png" },
    { id: "south-sudan", name: "South Sudan", flag: "https://flagcdn.com/256x192/ss.png" },
    { id: "spain", name: "Spain", flag: "https://flagcdn.com/256x192/es.png" },
    { id: "sri-lanka", name: "Sri Lanka", flag: "https://flagcdn.com/256x192/lk.png" },
    { id: "sudan", name: "Sudan", flag: "https://flagcdn.com/256x192/sd.png" },
    { id: "suriname", name: "Suriname", flag: "https://flagcdn.com/256x192/sr.png" },
    { id: "sweden", name: "Sweden", flag: "https://flagcdn.com/256x192/se.png" },
    { id: "switzerland", name: "Switzerland", flag: "https://flagcdn.com/256x192/ch.png" },
    { id: "syria", name: "Syria", flag: "https://flagcdn.com/256x192/sy.png" },
    { id: "taiwan", name: "Taiwan", flag: "https://flagcdn.com/256x192/tw.png" },
    { id: "tajikistan", name: "Tajikistan", flag: "https://flagcdn.com/256x192/tj.png" },
    { id: "tanzania", name: "Tanzania", flag: "https://flagcdn.com/256x192/tz.png" },
    { id: "thailand", name: "Thailand", flag: "https://flagcdn.com/256x192/th.png" },
    { id: "togo", name: "Togo", flag: "https://flagcdn.com/256x192/tg.png" },
    { id: "tonga", name: "Tonga", flag: "https://flagcdn.com/256x192/to.png" },
    { id: "trinidad-and-tobago", name: "Trinidad and Tobago", flag: "https://flagcdn.com/256x192/tt.png" },
    { id: "tunisia", name: "Tunisia", flag: "https://flagcdn.com/256x192/tn.png" },
    { id: "turkey", name: "Turkey", flag: "https://flagcdn.com/256x192/tr.png" },
    { id: "turkmenistan", name: "Turkmenistan", flag: "https://flagcdn.com/256x192/tm.png" },
    { id: "tuvalu", name: "Tuvalu", flag: "https://flagcdn.com/256x192/tv.png" },
    { id: "uganda", name: "Uganda", flag: "https://flagcdn.com/256x192/ug.png" },
    { id: "ukraine", name: "Ukraine", flag: "https://flagcdn.com/256x192/ua.png" },
    { id: "united-arab-emirates", name: "United Arab Emirates", flag: "https://flagcdn.com/256x192/ae.png" },
    { id: "united-kingdom", name: "United Kingdom", flag: "https://flagcdn.com/256x192/gb.png" },
    { id: "united-states", name: "United States", flag: "https://flagcdn.com/256x192/us.png" },
    { id: "uruguay", name: "Uruguay", flag: "https://flagcdn.com/256x192/uy.png" },
    { id: "uzbekistan", name: "Uzbekistan", flag: "https://flagcdn.com/256x192/uz.png" },
    { id: "vanuatu", name: "Vanuatu", flag: "https://flagcdn.com/256x192/vu.png" },
    { id: "vatican-city", name: "Vatican City", flag: "https://flagcdn.com/256x192/va.png" },
    { id: "venezuela", name: "Venezuela", flag: "https://flagcdn.com/256x192/ve.png" },
    { id: "vietnam", name: "Vietnam", flag: "https://flagcdn.com/256x192/vn.png" },
    { id: "yemen", name: "Yemen", flag: "https://flagcdn.com/256x192/ye.png" },
    { id: "zambia", name: "Zambia", flag: "https://flagcdn.com/256x192/zm.png" },
    { id: "zimbabwe", name: "Zimbabwe", flag: "https://flagcdn.com/256x192/zw.png" }
  ];
  

  